/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { CompanyUpdateManyWithoutUpdatesInput } from "./CompanyUpdateManyWithoutUpdatesInput";
import { ValidateNested, IsOptional, IsString, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Company } from "../../company/base/Company";
import { EventUpdateManyWithoutUpdatesInput } from "./EventUpdateManyWithoutUpdatesInput";
@InputType()
class UpdateUpdateInput {
  @ApiProperty({
    required: false,
    type: () => CompanyUpdateManyWithoutUpdatesInput,
  })
  @ValidateNested()
  @Type(() => CompanyUpdateManyWithoutUpdatesInput)
  @IsOptional()
  @Field(() => CompanyUpdateManyWithoutUpdatesInput, {
    nullable: true,
  })
  Company?: CompanyUpdateManyWithoutUpdatesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  Description?: string | null;

  @ApiProperty({
    required: false,
    type: () => EventUpdateManyWithoutUpdatesInput,
  })
  @ValidateNested()
  @Type(() => EventUpdateManyWithoutUpdatesInput)
  @IsOptional()
  @Field(() => EventUpdateManyWithoutUpdatesInput, {
    nullable: true,
  })
  product?: EventUpdateManyWithoutUpdatesInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantity?: number | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalPrice?: number | null;
}
export { UpdateUpdateInput };
